In [1]:
import numpy as np

**Tensor**
In the general case, an array of numbers arranged on a regular grid with a variable number of axes is known as a tensor.

In [37]:
# create tensor
T = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


For this 3D tensor, axis 0 specifies the level, axis 1 specifies the column, and axis 2 specifies the row.

In [23]:
a = np.array([
               [[4,1,2],[3,5,2],[1,6,7]],
               [[2,1,0],[5,4,3],[6,8,9]],
               [[1,2,3],[2,3,4],[5,5,5]]
             ])
b = np.array([[[1,1,1],[2,2,2],[3,3,3]],
               [[4,4,4],[5,5,5],[6,6,6]],
               [[7,7,7],[8,8,8],[9,9,9]]
             ])


In [36]:
a.ndim , a

(3, array([[[4, 1, 2],
         [3, 5, 2],
         [1, 6, 7]],
 
        [[2, 1, 0],
         [5, 4, 3],
         [6, 8, 9]],
 
        [[1, 2, 3],
         [2, 3, 4],
         [5, 5, 5]]]))

In [24]:
print(a+b)

[[[ 5  2  3]
  [ 5  7  4]
  [ 4  9 10]]

 [[ 6  5  4]
  [10  9  8]
  [12 14 15]]

 [[ 8  9 10]
  [10 11 12]
  [14 14 14]]]


In [38]:
print(a-b)

[[[ 3  0  1]
  [ 1  3  0]
  [-2  3  4]]

 [[-2 -3 -4]
  [ 0 -1 -2]
  [ 0  2  3]]

 [[-6 -5 -4]
  [-6 -5 -4]
  [-4 -4 -4]]]


## Tensor Hadamard Product
The element-wise multiplication of one tensor from another tensor with the same dimensions 

In [39]:
# tensor Hadamard product
A = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
C = A * B
print(C)


[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


## Tensor Division

In [40]:
D = A / B
print(D)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


## Tensor Product
The tensor product operator is often denoted as a circle with a small x in the middle. We will denote it here as “(x)”.

Given a tensor A with q dimensions and tensor B with r dimensions, the product of these tensors will be a new tensor with the order of q + r or, said another way, q + r dimensions.

a = (a1, a2)

b = (b1, b2)

c = a (x) b

c = (   a1 * [b1, b2]   
        a2 * [b1, b2])

c= (  a1 * b1, a1 * b2
      a2 * b1, a2 * b2)

In [43]:
# tensor product

A = np.array([1,2])
B = np.array([3,4])
C = np.tensordot(A, B, axes=0)

print(C)

[[3 4]
 [6 8]]


**tensor product for matrices**

     a11, a12
A = (a21, a22)

     b11, b12
B = (b21, b22)

C = A (x) B

            b11, b12          b11, b12
     a11 * (b21, b22), a12 * (b21, b22)
C = [       b11, b12          b11, b12 ]
     a21 * (b21, b22), a22 * (b21, b22)

In [48]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,1],[1,1]])
C = np.tensordot(A, B, axes=0)
print(C)

[[[[1 1]
   [1 1]]

  [[2 2]
   [2 2]]]


 [[[3 3]
   [3 3]]

  [[4 4]
   [4 4]]]]
